### ISSUE TITLE
간헐적으로 inference 결과가 저장된 후 API 서버가 재시작되는 문제

### ISSUE THREAD

**Issue by eunsoogi** [eunsoogi/kkalla#75]

**Comment by eunsoogi** [comment]
```bash
/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165
                        return fail(new QueryFailedError_1.QueryFailedError(query, parameters, err));
                                    ^

QueryFailedError: Data too long for column 'message' at row 1
    at Query.onResult (/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:165:37)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/app/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5) {
  query: 'INSERT INTO `notify`(`id`, `message`, `created_at`, `updated_at`, `user_id`) VALUES (?, ?, DEFAULT, DEFAULT, ?) RETURNING `id`, `created_at`, `updated_at`',
  parameters: [
    'eb24f6d4-4b47-4faa-a8e5-5b90bb68d5df',
    '추론 결과: `sell` (50%)\n' +
      '> 비트코인의 현재 가격 상승으로 인해 초과 평화익을 실현할 시점에 도달했다고 판단됩니다. 공포와 탐욕 지수의 상승에도 불구하고, 시장의 변동성이 커지며 손실 위험이 증가할 수 있습니다. 또한, 뉴스에서는 단기적인 고점이 형성될 가능성이 제기되고 있으며, 더 이상 상승하기 어려운 상황이 직면하고 있습니다. 적극적으로 가격 차익을 실현하고, 추가적으로 매도하여 재정비하는 것이 필요합니다. 현재 유동성을 확보하기 위한 전략이 필요하므로, 계좌 대조의 50%를 매도하는 것이 합리적입니다.',
    '9c4feb03-7e6d-422e-a9a6-2219c434fa5d'
  ],
  driverError: Error: Data too long for column 'message' at row 1
      at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:738:17)
      at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/app/node_modules/mysql2/lib/connection.js:481:34)
      at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:97:12)
      at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:104:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5) {
    code: 'ER_DATA_TOO_LONG',
    errno: 1406,
    sqlState: '22001',
    sqlMessage: "Data too long for column 'message' at row 1",
    sql: "INSERT INTO `notify`(`id`, `message`, `created_at`, `updated_at`, `user_id`) VALUES ('eb24f6d4-4b47-4faa-a8e5-5b90bb68d5df', '추론 결과: `sell` (50%)\\n> 비트코인의 현재 가격 상승으로 인해 초과 평화익을 실현할 시점에 도달했다고 판단됩니다. 공포와 탐욕 지수의 상승에도 불구하고, 시장의 변동성이 커지며 손실 위험이 증가할 수 있습니다. 또한, 뉴스에서는 단기적인 고점이 형성될 가능성이 제기되고 있으며, 더 이상 상승하기 어려운 상황이 직면하고 있습니다. 적극적으로 가격 차익을 실현하고, 추가적으로 매도하여 재정비하는 것이 필요합니다. 현재 유동성을 확보하기 위한 전략이 필요하므로, 계좌 대조의 50%를 매도하는 것이 합리적입니다.', DEFAULT, DEFAULT, '9c4feb03-7e6d-422e-a9a6-2219c434fa5d') RETURNING `id`, `created_at`, `updated_at`"
  },
  code: 'ER_DATA_TOO_LONG',
  errno: 1406,
  sqlState: '22001',
  sqlMessage: "Data too long for column 'message' at row 1",
  sql: "INSERT INTO `notify`(`id`, `message`, `created_at`, `updated_at`, `user_id`) VALUES ('eb24f6d4-4b47-4faa-a8e5-5b90bb68d5df', '추론 결과: `sell` (50%)\\n> 비트코인의 현재 가격 상승으로 인해 초과 평화익을 실현할 시점에 도달했다고 판단됩니다. 공포와 탐욕 지수의 상승에도 불구하고, 시장의 변동성이 커지며 손실 위험이 증가할 수 있습니다. 또한, 뉴스에서는 단기적인 고점이 형성될 가능성이 제기되고 있으며, 더 이상 상승하기 어려운 상황이 직면하고 있습니다. 적극적으로 가격 차익을 실현하고, 추가적으로 매도하여 재정비하는 것이 필요합니다. 현재 유동성을 확보하기 위한 전략이 필요하므로, 계좌 대조의 50%를 매도하는 것이 합리적입니다.', DEFAULT, DEFAULT, '9c4feb03-7e6d-422e-a9a6-2219c434fa5d') RETURNING `id`, `created_at`, `updated_at`"
}
```
